In [13]:
import pandas as pd
import numpy as np
import urllib.request as urllib2
from datetime import datetime, timedelta, date

### Get Oxford data and manipulate them

In [14]:
# Import Oxford data and enrich columns for future merging needs
df = pd.read_csv('https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv')
df['Date'] = pd.to_datetime(df['Date'], format="%Y%m%d")
df['DateString'] = df['Date'].apply(lambda x: datetime.strftime(x, "%Y%m%d"))
df['Index'] = df['CountryCode'] + df['DateString']

# Calculate Death Rates
df['DeathRate'] = df['ConfirmedDeaths'] / df['ConfirmedCases']
df

,CountryName,CountryCode,Date,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,C4_Restrictions on gatherings,...,M1_Wildcard,ConfirmedCases,ConfirmedDeaths,StringencyIndex,StringencyIndexForDisplay,LegacyStringencyIndex,LegacyStringencyIndexForDisplay,DateString,Index,DeathRate
0,Aruba,ABW,2020-01-01,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.00,20200101,ABW20200101,NaN
1,Aruba,ABW,2020-01-02,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.00,20200102,ABW20200102,NaN
2,Aruba,ABW,2020-01-03,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.00,20200103,ABW20200103,NaN
3,Aruba,ABW,2020-01-04,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.00,20200104,ABW20200104,NaN
4,Aruba,ABW,2020-01-05,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.00,20200105,ABW20200105,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20552,Kosovo,RKS,2020-05-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,856.0,26.0,NaN,83.6,NaN,82.14,20200505,RKS20200505,0.030374
20553,Kosovo,RKS,2020-05-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,856.0,26.0,NaN,83.6,NaN,82.14,20200506,RKS20200506,0.030374
20554,Kosovo,RKS,2020-05-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,861.0,27.0,NaN,83.6,NaN,82.14,20200507,RKS20200507,0.031359
20555,Kosovo,RKS,2020-05-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,861.0,27.0,NaN,83.6,NaN,82.14,20200508,RKS20200508,0.031359
20556,Kosovo,RKS,2020-05-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,862.0,28.0,NaN,83.6,NaN,82.14,20200509,RKS20200509,0.032483

### Get Market data and calculate Market Performance

In [15]:
stocks = pd.read_excel('Markets.xlsx')
stocks = stocks.groupby('CountryCode',sort=False).sum()
#stocks = stocks.rename({'United Kingdom': 'United Kingdom'}, axis='index')

stocks#.loc['United Kingdom']                                                    # TO BE DELETED

,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,2020-01-09,2020-01-10,2020-01-11,...,2020-04-06,2020-04-07,2020-04-08,2020-04-09,2020-04-10,2020-04-11,2020-04-12,2020-04-13,2020-04-14,2020-04-15
CountryCode,,,,,,,,,,,,,,,,,,,,,
CHN,3066.336,3089.022,3082.984333,3076.946667,3070.909000,3085.488,3094.239,3082.640,3102.294000,3098.693667,...,2796.533000,2806.968,2805.917,2825.839000,2827.187000,2812.990667,2798.794333,2784.598000,2794.801000,2826.662000
AUT,3187.620,3230.480,3225.186667,3219.893333,3214.600000,3202.490,3189.870,3195.910,3203.540000,3208.883333,...,1965.680000,2050.120,2126.690,2115.010000,2128.862000,2142.714000,2156.566000,2170.418000,2184.270000,2173.230000
BEL,3982.560,4002.170,3988.303333,3974.436667,3960.570000,3981.860,3965.680,4018.960,4025.000000,4025.410000,...,2964.960000,3035.720,3029.060,3105.800000,3110.754000,3115.708000,3120.662000,3125.616000,3130.570000,3044.730000
DNK,1254.213,1251.981,1247.004333,1242.027667,1237.051000,1240.099,1239.871,1240.858,1246.598000,1246.920333,...,1155.339000,1164.783,1154.511,1157.585167,1160.659333,1163.733500,1166.807667,1169.881833,1172.956000,1185.136000
FIN,4224.830,4282.380,4278.405000,4274.430000,4271.448750,4266.480,4254.830,4243.800,4240.300000,4247.033333,...,3325.930000,3428.230,3419.150,3481.770000,3491.776000,3501.782000,3511.788000,3521.794000,3531.800000,3531.740000
FRA,6016.610,6007.960,6005.710000,6003.460000,6001.210000,6033.220,5986.810,6066.750,6056.740000,6051.463333,...,4298.500000,4489.400,4397.360,4512.300000,4520.550000,4528.800000,4537.050000,4545.300000,4553.550000,4511.870000
ITA,23606.970,23709.900,23661.906667,23613.913333,23565.920000,23688.250,23550.610,23979.650,24061.430000,24061.436667,...,16769.130000,17587.810,17212.380,17685.560000,17712.824000,17740.088000,17767.352000,17794.616000,17821.880000,17454.940000
DEU,13233.710,13266.390,13206.090000,13145.790000,13085.490000,13199.590,13140.490,13474.760,13533.460000,13529.593333,...,9889.030000,10464.110,10301.560,10490.650000,10539.314000,10587.978000,10636.642000,10685.306000,10733.970000,10678.190000
GRC,917.990,926.110,923.820000,921.530000,919.812500,916.950,916.050,920.430,926.630000,925.676667,...,545.570000,589.960,606.200,610.690000,610.572000,610.454000,610.336000,610.218000,610.100000,625.880000
ISL,1516.420,1542.450,1537.006667,1531.563333,1526.120000,1518.950,1534.220,1532.430,1535.440000,1542.073333,...,1266.160000,1295.650,1328.480,1329.003333,1329.526667,1330.050000,1330.573333,1331.096667,1331.620000,1337.040000
IRL,7171.650,7314.390,7290.400000,7266.410000,7242.420000,7213.800,7238.180,7216.310,7258.230000,7263.580000,...,4787.890000,5017.730,5115.030,5109.840000,5148.820000,5187.800000,5226.780000,5265.760000,5304.740000,5183.570000
NLD,608.010,609.900,608.583333,607.266667,605.950000,609.830,607.530,614.020,614.150000,612.926667,...,486.260000,503.970,496.190,506.550000,507.674000,508.798000,509.922000,511.046000,512.170000,506.410000
POL,58122.410,58784.340,58737.687500,58691.035000,58656.045625,58597.730,58191.520,58062.050,58602.570000,58661.850000,...,42297.830000,44116.520,44042.590,43958.320000,44169.740000,44381.160000,44592.580000,44804.000000,45015.420000,46266.010000
PRT,5239.190,5246.930,5236.466667,5226.003333,5215.540000,5235.900,5207.960,5242.390,5240.060000,5247.583333,...,4028.570000,4094.350,4057.240,4109.580000,4142.900000,4176.220000,4209.540000,4242.860000,4276.180000,4234.530000
ESP,9639.100,9631.200,9615.933333,9600.666667,9585.400000,9623.100,9535.100,9629.200,9611.300000,9603.066667,...,6807.900000,6986.900,6930.200,7049.300000,7081.380000,7113.460000,7145.540000,7177.620000,7209.700000,7065.600000
SWE,1771.850,1806.412,1801.042750,1795.673500,1791.646563,1784.935,1795.149,1797.675,1797.516000,1793.815333,...,1443.364000,1493.775,1494.388,1518.815000,1521.021800,1523.228600,1525.435400,1527.642200,1529.849000,1531.472000
CHE,10585.290,10585.290,10607.786667,10630.283333,10652.780000,10714.230,10628.090,10721.870,10678.410000,10667.373333,...,9259.730000,9470.480,9427.410,9465.860000,9474.180000,9482.500000,9490.820000,9499.140000,9507.460000,9529.680000
GBR,7542.440,7604.300,7610.333333,7616.366667,7622.400000,7575.340,7573.850,7574.930,7598.120000,7594.696667,...,5415.500000,5582.390,5704.450,5677.730000,5710.716000,5743.702000,5776.688000,5809.674000,5842.660000,5791.310000
CAN,17137.650,17055.590,17047.236667,17038.883333,17030.530000,17119.500,17168.870,17205.960,17238.530000,17238.766667,...,13358.450000,13955.200,13719.660,14106.750000,14128.685000,14150.620000,14167.071250,14194.490000,14269.770000,14024.920000
USA,3244.670,3226.360,3223.423333,3220.486667,3217.550000,3241.860,3238.590,3266.030,3281.810000,3278.250000,...,2578.280000,2738.650,2685.000,2776.990000,2778.357500,2779.725000,2780.750625,2782.460000,2805.100000,2795.640000
AUS,6684.100,6690.600,6704.766667,6718.933333,6733.100000,6735.700,6826.400,6817.600,6874.200000,6892.466667,...,5067.500000,5286.800,5252.300,5206.900000,5242.980000,5279.060000,5315.140000,5351.220000,5387.300000,5488.100000
NZL,7528.440,7528.440,7553.643333,7578.846667,7604.050000,7631.570,7636.380,7589.780,7567.570000,7571.820000,...,6786.130000,6670.030,6666.000,6843.840000,6827.132000,6810.424000,6793.716000,6777.008000,6760.300000,6893.970000
HKG,28249.370,28828.360,28661.073333,28493.786667,28326.500000,28352.680,27999.580,28367.650,28665.140000,28700.883333,...,23558.830000,24093.050,24191.320,24181.320000,24214.578000,24247.836000,24281.094000,24314.352000,24347.610000,24499.860000
JPN,23319.760,23319.760,23319.760000,23319.760000,23319.760000,23320.120,23217.490,23530.290,23813.280000,23852.220000,...,17857.990000,18878.860,19047.760,19376.000000,19500.070000,19437.393333,19374.716667,19312.040000,19150.300000,19589.250000
KOR,2201.210,2192.580,2180.043333,2167.506667,2154.970000,2166.600,2156.270,2182.200,2189.480000,2194.483333,...,1745.250000,1826.720,1815.750,1838.090000,1835.760000,1841.606667,1847.453333,1853.300000,1846.410000,1864.802868
SGP,3230.480,3260.270,3247.366667,3234.463333,3221.560000,3236.230,3211.280,3262.720,3252.660000,3254.920000,...,2429.580000,2506.250,2528.310,2564.840000,2563.982500,2563.125000,2562.481875,2561.410000,2570.730000,2646.910000
TWN,12026.500,12167.440,12123.530000,12079.620000,12035.710000,11961.970,11818.760,11889.460,12009.270000,12029.383333,...,9707.750000,9928.160,10010.640,10173.260000,10105.430000,10119.473333,10133.516667,10147.560000,10130.650000,10366.770000
BRA,115652.000,118564.400,118278.500000,117992.600000,117706.700000,116871.700,116667.300,116247.500,115947.800000,115799.366667,...,69555.600000,74078.000,76334.800,78639.700000,78400.250000,78160.800000,77981.212500,77681.900000,78847.700000,79911.300000
ISR,1684.230,1684.190,1684.150000,1684.110000,1682.230000,1682.440,1672.620,1678.540,1678.423333,1678.306667,...,1278.040000,1328.370,1337.182,1345.994000,1354.806000,1363.618000,1372.430000,1347.210000,1353.460214,1366.942602
IND,41340.270,41634.510,41549.120000,41463.730000,41378.340000,40983.040,40574.830,41216.670,41568.200000,41641.536667,...,28812.475625,28898.360,29701.920,30571.190000,30727.322500,30883.455000,31000.554375,31195.720000,31236.415000,31277.110000
MEX,43739.520,44355.210,44400.130000,44445.050000,44489.970000,44522.360,44160.550,44452.740,44593.890000,44636.043333,...,33641.070000,34688.320,34625.070,34638.862000,34652.654000,34666.446000,34680.238000,34694.030000,34765.510000,34593.580000
ZAF,57084.100,57718.000,57748.666667,57779.333333,57810.000000,57195.350,57384.410,57322.330,57128.680000,57247.400000,...,44598.700000,46240.350,47496.720,46689.900000,46954.232000,47218.564000,47482.896000,47747.228000,48011.560000,49874.510000
RUS,5344.450,5344.450,5363.750000,5383.050000,5402.350000,5406.105,5409.860,5434.650,5476.250000,5485.183333,...,4507.070000,4594.950,4617.970,4665.380000,4750.380000,4732.546667,4714.713333,4696.880000,4594.750000,4585.070000
NOR,851.570,853.470,852.194545,850.919090,853.290000,849.340,850.520,849.550,850.690000,851.106618,...,668.340000,679.050,669.310,677.151467,679.106051,680.503630,681.881134,682.782414,689.260000,674.940000

In [16]:
# Reference dates: 23rd and 24th March 2020

market0 = stocks[datetime(2020, 3, 23, 0, 0)]
for i in (8, 9, 10, 16, 17, 20, 21, 27, 29, 30, 31, 32):                            #range(1,len(stocks)):
    market0.iloc[i] = stocks[datetime(2020, 3, 24, 0, 0)][i]

market0.head()         # TO BE DELETED

CountryCode
CHN    2677.591
AUT    1888.070
BEL    2675.760
DNK     989.325
FIN    2939.290
Name: 2020-03-23 00:00:00, dtype: float64

In [17]:
# Market Performance
mkt_p = stocks.T/market0 -1
mkt_p = mkt_p.T
#mkt_p = mkt_p.reindex(focuscountries)

# showing perfomances from 23rd March onward
mkt_p.iloc[:, 81::].head()        # TO BE DELETED

,2020-03-23,2020-03-24,2020-03-25,2020-03-26,2020-03-27,2020-03-28,2020-03-29,2020-03-30,2020-03-31,2020-04-01,...,2020-04-06,2020-04-07,2020-04-08,2020-04-09,2020-04-10,2020-04-11,2020-04-12,2020-04-13,2020-04-14,2020-04-15
CountryCode,,,,,,,,,,,,,,,,,,,,,
CHN,0.0,0.009497,0.036493,0.031485,0.043096,0.036465,0.029834,0.023203,0.033506,0.024630,...,0.044421,0.048318,0.047926,0.055366,0.055870,0.050568,0.045266,0.039964,0.043774,0.055674
AUT,0.0,-0.003374,0.077778,0.068890,0.089245,0.079409,0.069574,0.059738,0.053970,0.059405,...,0.041105,0.085828,0.126383,0.120197,0.127533,0.134870,0.142207,0.149543,0.156880,0.151033
BEL,0.0,0.044477,0.113975,0.066273,0.095827,0.086116,0.076406,0.066695,0.070216,0.060088,...,0.108081,0.134526,0.132037,0.160717,0.162568,0.164420,0.166271,0.168123,0.169974,0.137894
DNK,0.0,0.037071,0.080943,0.066369,0.091324,0.093001,0.094678,0.096355,0.148118,0.124499,...,0.167805,0.177351,0.166968,0.170076,0.173183,0.176290,0.179398,0.182505,0.185612,0.197924
FIN,0.0,0.024754,0.096363,0.091202,0.119702,0.111906,0.104109,0.096312,0.117113,0.114735,...,0.131542,0.166346,0.163257,0.184562,0.187966,0.191370,0.194774,0.198178,0.201583,0.201562

In [18]:
# Converting Market Performances data from rows to columns
mkt_p1 = pd.DataFrame(mkt_p[mkt_p.columns[0]])
mkt_p1['Date'] = mkt_p1.columns.repeat(len(mkt_p1))
mkt_p1.rename(columns={mkt_p1.columns[0]:'MarketPerformance', 'Date':'Date'}, inplace=True)

for i in range(1, len(mkt_p.columns)):
    mkt_p_new = pd.DataFrame(mkt_p[mkt_p.columns[i]])
    mkt_p_new['Date'] = mkt_p_new.columns.repeat(len(mkt_p))
    mkt_p_new.rename(columns={mkt_p_new.columns[0]:'MarketPerformance', 'Date':'Date'}, inplace=True)
    mkt_p1 = pd.concat([mkt_p1, mkt_p_new], axis=0)

mkt_p1.head()

             MarketPerformance       Date
CountryCode
CHN                   0.145185 2020-01-02
AUT                   0.688295 2020-01-02
BEL                   0.488385 2020-01-02
DNK                   0.267746 2020-01-02
FIN                   0.437364 2020-01-02

In [19]:
# Adding columns needed for merging with Oxford data
mkt_p1['DateString'] = mkt_p1['Date'].apply(lambda x: datetime.strftime(x, "%Y%m%d"))
mkt_p1['Index'] = mkt_p1.index + mkt_p1['DateString']
mkt_p1.loc['USA']

             MarketPerformance       Date DateString        Index
CountryCode
USA                   0.416447 2020-01-02   20200102  USA20200102
USA                   0.408454 2020-01-03   20200103  USA20200103
USA                   0.407172 2020-01-04   20200104  USA20200104
USA                   0.405890 2020-01-05   20200105  USA20200105
USA                   0.404608 2020-01-06   20200106  USA20200106
...                        ...        ...        ...          ...
USA                   0.213477 2020-04-11   20200411  USA20200411
USA                   0.213925 2020-04-12   20200412  USA20200412
USA                   0.214671 2020-04-13   20200413  USA20200413
USA                   0.224555 2020-04-14   20200414  USA20200414
USA                   0.220425 2020-04-15   20200415  USA20200415

[105 rows x 4 columns]

In [20]:
# Add Market Performance to Oxford file 
df = df.merge(mkt_p1, left_on = 'Index', right_on = 'Index', how = 'left')
df[df['CountryCode']=='USA']

,CountryName,CountryCode,Date_x,C1_School closing,C1_Flag,C2_Workplace closing,C2_Flag,C3_Cancel public events,C3_Flag,C4_Restrictions on gatherings,...,StringencyIndex,StringencyIndexForDisplay,LegacyStringencyIndex,LegacyStringencyIndexForDisplay,DateString_x,Index,DeathRate,MarketPerformance,Date_y,DateString_y
19248,United States,USA,2020-01-01,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.00,0.00,0.00,0.00,20200101,USA20200101,NaN,NaN,NaT,NaN
19249,United States,USA,2020-01-02,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.00,0.00,0.00,0.00,20200102,USA20200102,NaN,0.416447,2020-01-02,20200102
19250,United States,USA,2020-01-03,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.00,0.00,0.00,0.00,20200103,USA20200103,NaN,0.408454,2020-01-03,20200103
19251,United States,USA,2020-01-04,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.00,0.00,0.00,0.00,20200104,USA20200104,NaN,0.407172,2020-01-04,20200104
19252,United States,USA,2020-01-05,0.0,NaN,0.0,NaN,0.0,NaN,0.0,...,0.00,0.00,0.00,0.00,20200105,USA20200105,NaN,0.405890,2020-01-05,20200105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19374,United States,USA,2020-05-06,3.0,1.0,3.0,0.0,2.0,0.0,4.0,...,71.58,71.58,73.57,73.57,20200506,USA20200506,0.059012,NaN,NaT,NaN
19375,United States,USA,2020-05-07,3.0,1.0,3.0,0.0,2.0,0.0,4.0,...,71.58,71.58,73.57,73.57,20200507,USA20200507,0.059768,NaN,NaT,NaN
19376,United States,USA,2020-05-08,3.0,1.0,3.0,0.0,2.0,0.0,4.0,...,71.58,71.58,73.57,73.57,20200508,USA20200508,0.060200,NaN,NaT,NaN
19377,United States,USA,2020-05-09,3.0,1.0,3.0,0.0,2.0,0.0,4.0,...,71.58,71.58,73.57,73.57,20200509,USA20200509,0.060112,NaN,NaT,NaN
19378,United States,USA,2020-05-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,71.58,NaN,73.57,20200510,USA20200510,0.060169,NaN,NaT,NaN